Feature: HomePage Page

  @tag5
  Scenario: login to application with valid username and password. UserMenu page is displayed and dropdown is validated
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    Then user click dropDown "userMenuDropDown"
    Then I validate the list "userMenuDropDownList"

  @tag6
  Scenario: login to application with valid username and password.Select My Profile option from user menu for user drop down.
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And user click dropDown "userMenuDropDown"
    And click on the button "MyProfile"
    Given user is on "MyProfilePage"
    Then click on the button "editProfile"
    Then user switch frame "aboutSwitchFrame"
    And click on the button "aboutTab"
    When user enter into textbox "lastName" "Ram"
    And click on the button "saveAll"
    Given user is on "MyProfilePage"
    And click on the button "Post"
    Then user switch frame "postSwitchFrame"
    When user post a message "postMsg" "This is a Cucumber Framework test message"
    And click on the button "Share"
    Given user is on "MyProfilePage"
    When click on the button "file"
    Then click on the button "upload"
    When user choose file "chooseFile" "/Users/rahade/Documents/Personal/Tekarch/PointsToRemember/NotesToRem.rtf"
    And click on the button "publishersharebutton"
    Given user is on "MyProfilePage"
    Then user move to element "photo"
    Then user switch frame "photoSwitchFrame"
    When user choose file "choosePhoto" "/Users/rahade/Documents/Personal/Tekarch/Pics/1.jpg"
    And click on the button "clickSavePhoto"
    #Then crop the image "cropper1"
    #Then crop the image "cropper2"
    And click on the button "saveCroppedImg"

  @tag7
  Scenario: Select My settings option from user menu for username drop down
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And user click dropDown "userMenuDropDown"
    And click on the button "MySettings"
    Given user is on "MySettingsPage"
    Then click on the button "personalBtn"
    And click on the button "loginHistory"
    Then click on the button "downloadLoginHistory"
    When click on the button "displayLayout"
    And click on the button "customizeTab"
    And user click dropDown "clickDropDown"
    Then user select by visible text "clickDropDown" "Salesforce Chatter"
    Then user select by visible text "selectReports" "Reports"
    When click on the button "clickAddReport"
    Then click on the button "clickSaveReport"
    And click on the button "email"
    Then click on the button "myEmailSettings"
    When user enter into textbox "emailName" "Deepika Ram"
    And user enter into textbox "emailAddress" "deepikark8@gmail.com"
    Then click on the button "AutomaticBcc"
    Then click on the button "saveBtn"
    Then click on the button "calender"
    Then click on the button "clickActivityReminders"
    Then click on the button "OpenaTestReminder"
    Then I validate the title "title" "Activity Reminders ~ Salesforce - Developer Edition"

  @tag8
  Scenario: Select Developers Console option from user menu for username drop down
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And user click dropDown "userMenuDropDown"
    Then click on the button "developerConsole"
    When pop Window Opens
    Then I validate the title "title" "Developer Console"

  @tag9
  Scenario: Select Logout option from user menu for username drop down
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And user click dropDown "userMenuDropDown"
    Then click on the button "logout"
