Feature: Random Scenario

  @tag33
  Scenario: Verify if the firstname and lastname of the loggedin user is displayed
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And click on the button "elementHome"
    Then click on the button "close"
    Then I validate the actual and expected text "elementUserNameInUseMenu" "elementUserName"
    Then user move to element "elementUserName"
    Then I validate the title "title" "User: Deepika Ram ~ Salesforce - Developer Edition"

  @tag34
  Scenario: Verify the edited lastname is updated at various places
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And click on the button "elementHome"
    Then click on the button "close"
    And click on the button "elementUserName"
    And click on the button "editProfile"
    Given user is on "MyProfilePage"
    Then user switch frame "aboutSwitchFrame"
    And click on the button "aboutTab"
    When user enter into textbox "lastName" "Abcd"
    And click on the button "saveAll"
    Given user is on "HomePage"
    Then I validate the text "elementUserNameTitle" "Deepika Abcd "

  @tag35
  Scenario: Verify the tab customization
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And click on the button "clickAllTab"
    Then click on the button "elementCustomizeAllTabs"
    Then user select by visible text "elementSelectedTab" "Opportunities"
    And click on the button "elementClickSaveBtn"
    Given user is on "HomePage"
    And user click dropDown "userMenuDropDown"
    Then click on the button "logout"
    Then sleep time
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    Then validate the tab name "elementHomeTabNames" "Opportunities"

  @tag36
  Scenario: Blocking an event in the calender
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And click on the button "elementHome"
    Then click on the button "close"
    Then I validate the text "elementUserProfileName" "Deepika Abcd"
    Then click on the button "elementDateLink"
    Then I validate the title "title" "Calendar for Deepika Abcd ~ Salesforce - Developer Edition"
    Then click on the button "element8PM"
    Then I validate the title "title" "Calendar: New Event ~ Salesforce - Developer Edition"
    And click on the button "elementSubjectComboBoxBtn"
    Then validate combo box window "elementOtherLink" "Other"
    Then click on the button "elementEndTime"
    Then click on the button "elementClick9"
    Then click on the button "elementCalenderSave"
    Then I validate the text "elementTime8PM" "8:00 PM"
    Then I validate the text "elementOther8PM" "Other"

  @tag37
  Scenario: Blocking an event in the calender with weekly recurrance
    Given user is on "LoginPage"
    When user enter into textbox "username" "deepika@mh.com"
    Then user enter into textbox "password" "password@123"
    And click on the button "Login"
    Given user is on "HomePage"
    And click on the button "elementHome"
    Then click on the button "close"
    Then I validate the text "elementUserProfileName" "Deepika Abcd"
    Then click on the button "elementDateLink"
    Then I validate the title "title" "Calendar for Deepika Abcd ~ Salesforce - Developer Edition"
    Then click on the button "element4PM"
    Then I validate the title "title" "Calendar: New Event ~ Salesforce - Developer Edition"
    And click on the button "elementSubjectComboBoxBtn"
    Then validate combo box window "elementOtherLink" "Other"
    Then click on the button "elementEndTime"
    Then click on the button "elementClick9"
    And click on the button "elementCheckRecurrence"
    Then I validate the text "elementFrequency" "Frequency"
    Then I validate the text "elementStartDate" "Recurrence Start"
    Then I validate the text "elementEndDate" "Recurrence End"
    And click on the button "elementSelectWeekly"
    When user enter  end date into textbox "EndDate" "14"
    Then click on the button "elementCalenderSave"
    Then I validate the text "elementTime" "4:00 PM"
    Then I validate the text "elementOther4PM" "Other"
    Then click on the button "elementMonthView"
